name: Build for MIPS64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++-mips64-linux-gnuabi64 make

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build statically linked binary
        run: make CC=mips64-linux-gnuabi64-gcc

      - name: Output binary as base64
        run: |
          echo "::group::BEGIN BASE64 OUTPUT"
          base64 -w 0 ./udp-broadcast-relay
          echo "::endgroup::"
